/*  XPlotterSVG - Convert SVG to GCode
    Copyright (C) 2017  Samuel Pickard
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>. */
package am.fats;

import org.w3c.dom.Document;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayDeque;
import java.util.ArrayList;

public class SVGParser extends DefaultHandler
{

    protected FileLineWriter mGCode;
    protected BufferingGCodeWriter mBody;
    protected TransformationStack mTrans;
    protected SVGElement[] mElements = { new SVGCircle(), new SVGEllipse(), new SVGPolyline(), new SVGPath(),
                        new SVGGroup(), new SVGLine(), new SVGPolygon(), new SVGRect(), new SVGImage()};
    protected SVGSvg mSVGElement = new SVGSvg();
    org.xml.sax.XMLReader mSVGReader;

    public void process(String inputSVGFileName, FileLineWriter gcode, Boolean pause) throws IOException
    {
        // The real output stream the caller gave us. Header, framing pass and
        // M0 will be written directly to this. The body of the job (everything
        // emitted while parsing the SVG) is captured into a buffer first so we
        // can compute its true bounding box.
        // Everything is rewritten into the form the Falcon runs straight
        // through from its card, without stopping for the button
        FalconGCodeWriter realOut = new FalconGCodeWriter(gcode);
        BufferingGCodeWriter buffer = new BufferingGCodeWriter();

        mTrans = new TransformationStack();

        // --- Header (straight to real output) ---
        mGCode = realOut;
        StringBuilder com = new StringBuilder();
        com.append("Generated by XPlotterSVG version ");
        com.append(Version.version());
        GCodeComment opening = new GCodeComment(com.toString());
        mGCode.writeLine(opening.toString());

        if(!pause)
            mGCode.writeLine("M0"); //Disable screen
        mGCode.writeLine("G21"); //Units in mm
        mGCode.writeLine("G90"); //All positions are absolute
        mGCode.writeLine("G17"); //XY plane
        mGCode.writeLine("G54"); //Default work coordinate system
        mGCode.writeLine("G28"); //Reset to origin
        mGCode.writeLine("M4"); //Enable laser mode (dynamic power)
        mGCode.writeLine("S0"); //Laser off

        // --- Body (captured into buffer; nothing goes to real output yet) ---
        mGCode = buffer;
        mBody = buffer;

        SAXParserFactory spf = SAXParserFactory.newInstance();
        spf.setNamespaceAware(true);
        SAXParser saxParser;
        try {
            saxParser = spf.newSAXParser();

            //Open the input SVG
            mSVGReader = saxParser.getXMLReader();
            try {
                mSVGReader.setContentHandler(this);
                mSVGReader.parse(inputSVGFileName);
            } catch (IOException e) {
                System.out.print("Cannot open SVG file "); System.out.println(inputSVGFileName);
                e.printStackTrace();
                return;
            }

        } catch (ParserConfigurationException e) {
            e.printStackTrace();
        } catch (SAXException e) {
            e.printStackTrace();
        }

        //Cut inner features before the outlines that contain them, so a
        //piece isn't freed (and free to drop or twist) until it's finished
        int moved = buffer.reorderInsideOut();
        if(moved > 0)
            System.out.println(String.format("Reordered %d shapes to cut inner features before their outlines", moved));

        //Switch off tool at end-of-job (still appended to buffer, after every shape)
        buffer.endBody();
        if(Tool.currentTool() == Tool.TOOL_LASER)
        {
            GCodeLaserOff off = new GCodeLaserOff();
            mGCode.writeLine(off.toString());
            mGCode.writeLine("M5");
        }
        else if(PlotterState.isHeadDown())
        {
            GCodePenUp up = new GCodePenUp();
            mGCode.writeLine(up.toString());
        }

        // --- Framing pass (real output, computed from observed bounds) ---
        mGCode = realOut;
        if (buffer.hasBounds()) {
            drawBoundaryBox(buffer.getMinX(), buffer.getMinY(),
                            buffer.getMaxX(), buffer.getMaxY());
        } else {
            // No geometry was emitted; fall back to the SVG viewBox so the
            // operator still sees something happen.
            Point2D vb = PlotterState.getViewBox();
            drawBoundaryBox(0, 0, vb.x, vb.y);
        }
        GCodeComment frameComment = new GCodeComment("Framing complete - press cycle-start to begin cutting");
        mGCode.writeLine(frameComment.toString());
        mGCode.writeLine("M0"); //Pause until operator resumes (GRBL: cycle-start)

        // --- Replay the captured body to the real output ---
        buffer.flushTo(realOut);

        // --- Footer (real output) ---
        mGCode.writeLine("G28"); //Reset to origin
        if(!pause)
            mGCode.writeLine("M1");
        realOut.finish();
        realOut.close();
    }

    public void startElement(String namespaceURI, String localName, String qName, Attributes atts)
    {
        //Special case for an SVG element to get the viewbox dimensions
        if(localName.contentEquals("svg"))
        {
            try {
                mSVGElement.process(atts, mGCode);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        ArrayList<CutSpecification> specs = findSpecfication(atts);

        //Another special case - TODO: redesign
        if(localName.toLowerCase().contentEquals("image"))
        {
            specs = Material.getSpecification("raster");
        }

        // Falcon laser-only: ignore any pen specs so we never emit pen G-code
        if(specs != null && !specs.isEmpty())
        {
            ArrayList<CutSpecification> laserOnly = new ArrayList<CutSpecification>();
            for(CutSpecification spec : specs)
            {
                if(spec != null && spec.getTool() == Tool.TOOL_LASER)
                {
                    laserOnly.add(spec);
                }
            }
            specs = laserOnly;
        }

        for(SVGElement elem : mElements)
        {
            if(elem.acceptsElement(localName))
            {
                //This is the static setup method
                elem.preProcess(atts);

                //There might be multiple specs, so process for each
                for(CutSpecification spec : specs) {
                    //Everything for this shape and spec moves as one unit
                    //if the body is later reordered
                    if(mBody != null)
                        mBody.beginShape();
                    try {
                        configureTool(spec);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }

                    //Only process if we have a material spec. We have to go this far
                    //because we might need the transformations, even if there is nothing
                    //to plot.
                    if (spec != null) {
                        for (int i = 0; i < spec.getRepeat(); i++) {
                           //This is the instance method
                            try {
                                elem.process(atts, mGCode);
                            } catch (IOException e) {
                                e.printStackTrace();
                            }

                        }
                        //Process any dwell command
                        if(spec.getDwell() > 0)
                        {
                            GCodeDwell dwell = new GCodeDwell(spec.getDwell());
                            try {
                                mGCode.writeLine(dwell.toString());
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    //A path can finish with the laser still on, leaving the
                    //next shape's travel move to switch it off. Close it here
                    //so the shape is safe to cut in any order.
                    if(PlotterState.isHeadDown() && Tool.currentTool() == Tool.TOOL_LASER)
                    {
                        try {
                            mGCode.writeLine(new GCodeLaserOff().toString());
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                    if(mBody != null)
                        mBody.endShape();
                }
            }
        }

    }

    public void endElement(String uri, String localName, String qName)
    {
        //TODO:  I can see that this is a massive hack.
        //really it needs to be a proper reentrant recursive routine
        //but the SAX parser doesn't work like that.  I need to think about
        //how to process the SVG because its the SAX that is letting me down.

        //We have to check again to see if we recognise this element
        for(SVGElement elem : mElements)
        {
            if (elem.acceptsElement(localName))
            {
                elem.postProcess();
            }
        }
    }

    protected ArrayList<CutSpecification> findSpecfication(Attributes atts)
    {
        ArrayList<CutSpecification> spec = new ArrayList<CutSpecification>();

        // An inline style's stroke takes precedence over the presentation
        // attribute, matching CSS specificity. Inkscape often leaves a stale
        // stroke="..." attribute alongside the real style stroke, so prefer
        // the style and only fall back to the attribute when it has no stroke.
        String hexcode = "";
        String style = atts.getValue("style");
        if(style != null && style.length() > 0)
        {
            String[] styles = style.split(";");
            for(String harry : styles)
            {
                String[] nvp = harry.split(":");
                if(nvp.length >= 2 && nvp[0].trim().contentEquals("stroke"))
                {
                    hexcode = nvp[1].trim();
                }
            }
        }

        if(hexcode.length() == 0)
        {
            String attr = atts.getValue("stroke");
            if(attr != null)
                hexcode = attr;
        }

        if(hexcode.length() > 0)
            spec = Material.getSpecification(hexcode);

        return spec;
    }

    /**
     * Traces a rectangle around the supplied bounds with the laser off, so
     * the operator can verify material placement before the actual job
     * begins. The supplied coordinates are in machine space (post-transform,
     * post-Y-flip) and are emitted as raw G0 moves directly, bypassing the
     * {@link GCodeMove} pipeline so they are not transformed a second time.
     *
     * @param minX bottom-left X
     * @param minY bottom-left Y
     * @param maxX top-right X
     * @param maxY top-right Y
     */
    protected void drawBoundaryBox(double minX, double minY, double maxX, double maxY) throws IOException {
        java.text.DecimalFormatSymbols sym = new java.text.DecimalFormatSymbols(java.util.Locale.getDefault());
        sym.setDecimalSeparator('.');
        java.text.DecimalFormat df = new java.text.DecimalFormat("0.####", sym);
        df.setGroupingUsed(false);

        // Make sure laser is off
        GCodeLaserOff laserOff = new GCodeLaserOff();
        mGCode.writeLine(laserOff.toString());

        // Set framing feedrate
        mGCode.writeLine("G1 F1200");

        // Trace the bounding box (clockwise from bottom-left)
        mGCode.writeLine("G0 X" + df.format(minX) + " Y" + df.format(minY) + " F1200");
        mGCode.writeLine("G0 X" + df.format(maxX) + " Y" + df.format(minY) + " F1200");
        mGCode.writeLine("G0 X" + df.format(maxX) + " Y" + df.format(maxY) + " F1200");
        mGCode.writeLine("G0 X" + df.format(minX) + " Y" + df.format(maxY) + " F1200");
        mGCode.writeLine("G0 X" + df.format(minX) + " Y" + df.format(minY) + " F1200");
    }
    
    protected void configureTool(CutSpecification spec) throws IOException {
        if(spec == null)
            return;

        // Falcon laser-only
        Tool.setTool(Tool.TOOL_LASER);

        //Power in materials is raw S value (0..1000)
        Tool.setPower(spec.getPower());

        //Set the feedrate
        Tool.setFeedrate(spec.getFeedrate());

        //Emit modal setup for this cut spec
        mGCode.writeLine(String.format("G1 F%d", spec.getFeedrate()));
    }
}
